# FROM node:22-alpine AS base
# WORKDIR /app
# COPY ./package*.json ./
# RUN npm ci

# FROM base AS dev
# RUN npm install --only=dev
# COPY ./ .
# RUN npm run lint
# RUN npm run test

# FROM base AS build
# COPY --from=dev /app /app
# RUN npm run build

# FROM node:22-alpine AS prod
# WORKDIR /app
# COPY --from=base /app/node_modules ./node_modules
# COPY --from=build /app/dist ./dist
# COPY --from=build /app/client ./client

# EXPOSE 3000
# CMD ["node", "dist/main"]

FROM node:22-alpine AS base
WORKDIR /app
COPY ./ .
RUN npm ci

FROM base AS build
COPY --from=base /app /app
RUN npm run build

FROM node:22-alpine AS prod
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/client ./client

EXPOSE 3000
CMD ["node", "dist/main"]
