services:
  postgres:
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    env_file:
      - path: .docker-env
        required: true
  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - path: .docker-env
        required: true
